# Generated by Django 4.1.3 on 2022-11-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.BigIntegerField()),
                ("fill_price", models.BigIntegerField()),
                ("fill_quantity", models.FloatField()),
                ("side", models.TextField()),
                ("exchange", models.TextField()),
                ("symbol", models.TextField()),
                ("fees", models.FloatField()),
                ("timestamp", models.DateTimeField()),
            ],
            options={"db_table": "fills",},
        ),
    ]
