# Generated by Django 4.1.3 on 2022-11-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fills", name="timestamp", field=models.BigIntegerField(),
        ),
    ]
